name: "Docker Build"
description: "Builds and tests Docker images"
inputs:
  image-name:
    required: true
    description: "Docker image name"
  context:
    required: false
    default: "."
    description: "Build context path"
  dockerfile:
    required: false
    default: "Dockerfile"
    description: "Path to Dockerfile"
  runner:
    required: false
    default: "ubuntu-latest"
    description: "Runner label"
  platforms:
    required: false
    default: "linux/amd64,linux/arm64"
    description: "Target platforms"
  push-image:
    required: false
    default: "false"
    description: "Push to registry"

runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        platforms: ${{ inputs.platforms }}
        push: ${{ inputs.push-image }}
        tags: ${{ inputs.image-name }}:pr-check
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Test container startup
      if: inputs.push-image == 'false'
      shell: bash
      run: |
        echo "🧪 Testing container startup..."
        echo "Build successful. Skipping runtime test for multi-arch build."
